=== daw2-mtz22/M9_P0_MartinezAaron/M4_P1_CinesLlefia/src/assets/peliculas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="peliculas" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pelicula">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="imagenPortada" type="xs:string"/>
                            <xs:element name="imagenCentral" type="xs:string"/>
                            <xs:element name="trailer" type="xs:string" minOccurs="0"/>
                            <xs:element name="duracion">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="500"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="pais" type="xs:string"/>
                            <xs:element name="generos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="genero" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="estreno">
                                <xs:simpleType>
                                    <xs:restriction base="xs:date">
                                        <xs:minInclusive value="2010-01-01"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="directores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="director" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="guionistas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="guionista" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="productores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="productor" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="actores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="actor" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="estrellas">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="5"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="votos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="1000000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sinopsis">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="parrafo" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== daw2-mtz22/M9_P0_MartinezAaron/M4_CinesLlefia/assets/peliculas.xml
<?xml version="1.0" encoding="UTF-8"?>
<peliculas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="peliculas.xsd">
    <pelicula>
        <titulo>Moneyball</titulo>
        <imagenPortada>"./assets/moneyball-portada.jpg"</imagenPortada>
        <imagenCentral>"./assets/moneyball_grande.jpg"</imagenCentral>
        <duracion>133</duracion>
        <pais>Estados Unidos</pais>
        <generos>
            <genero>Deporte</genero>
            <genero>Basado en hechos reales</genero>
        </generos>
        <estreno>2012-02-03
        </estreno>
        <directores>
            <director>Bennett Miller</director>
        </directores>
        <guionistas>
            <guionista>Aaron Sorkin</guionista>
            <guionista>Steven Zaillian</guionista>
        </guionistas>
        <productores>
            <productor>Columbia Pictures</productor>
            <productor>Michael De Luca</productor>
            <productor>Scott Rudin Productions</productor>
            <productor>Specialty Films</productor>
        </productores>
        <actores>
            <actor>Brad Pitt</actor>
            <actor>Jonahan Hill</actor>
            <actor>Philip Seymour Hoffman</actor>
            <actor>Robin Wright</actor>
            <actor>Stephen Bishop</actor>
            <actor>Chris Pratt</actor>
        </actores>
        <estrellas>4</estrellas>
        <votos>37047</votos>
        <sinopsis>
            <parrafo>En 2001, Billy Beane (Brad Pitt), director general de los Atléticos de Oakland (béisbol), se hizo famoso al conseguir grandes éxitos por medio del método "Moneyball", programa que consiste en construir un equipo competitivo con menos recursos económicos que la mayoría de los equipos de las Grandes Ligas y empleando métodos estadísticos por ordenador para coordinar a los jugadores.</parrafo></sinopsis>
    </pelicula>
</peliculas>
